### ISSUE TITLE
Unable to mount volume on k8s 1.17

### ISSUE THREAD

**Issue by kidhasmoxy** [jparklab/synology-csi#18] opened 2020-01-28 18:19 UTC
Using the 1.16 deployment. Simple 1gb PVC on a test deployment. 

Startup cycles with the following errors: 

Warning | FailedMount | MountVolume.SetUp failed for volume "pvc-691477a2-ee2c-4c8e-ac82-66bfba218f2b" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Unable to list existing sessions: exit status 21 | a minute ago
-- | -- | -- | --
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[1gb], unattached volumes=[1gb default-token-cdhl5]: timed out waiting for the condition | 2 minutes ago

running on ubuntu 18.04

**Comment by jparklab** [comment] 2020-01-29 02:57
Do you have an iscsi package installed on the host? What do you get when you run `sudo iscsiadm -m session` on the host? The csi driver uses iscsi tools installed on the host, and, thus, mount will fail if host does not have iscsi package installed.

**Comment by kidhasmoxy** [comment] 2020-02-01 01:19
` sudo iscsiadm -m session
`
gives: 
iscsiadm: No active sessions.


I also see the following in the log:

I0201 01:18:26.544598 1 iscsi.go:72] [EXECUTING] -m discovery -t sendtargets -p NASDNSNAME
I0201 01:18:26.696929 1 iscsi.go:90] [EXECUTING] -m session
I0201 01:18:26.699558 1 iscsi.go:94] Error running iscsiadm session: exit status 21
I0201 01:18:26.699599 1 nodeserver.go:125] Unable to list existing sessions: exit status 21
E0201 01:18:26.699608 1 utils.go:100] GRPC error: rpc error: code = Internal desc = Unable to list existing sessions: exit status 21

**Comment by kidhasmoxy** [comment] 2020-02-01 01:48
It seems as though the issue is here: https://github.com/jparklab/synology-csi/blob/14a901deea974511c49fa34716741118def0d785/pkg/driver/nodeserver.go#L120

We're checking for a session and expecting no error code, but isciadm will return an exit code of 21 (ISCSI_ERR_NO_OBJS_FOUND) if there are no active sessions, which should be ok. 

Here's a similar example from Trident that shows handling the error: 
https://github.com/NetApp/trident/blob/f74ce51709e40bec0c5c7c2b9693a448999abfc3/utils/osutils.go#L972

**Comment by brianbuquoi** [comment] 2020-02-01 03:52
I'm also seeing this on 1.17. Everything successfully will work if I have a node cordoned, but as soon as I uncordon and attempt to move a pod to another node, I receive this error. csi-plugin logs show the same as above.

**Comment by jparklab** [comment] 2020-02-01 21:48
@kidhasmoxy thanks for the reference. @bokysan fixed nodeserver.go(https://github.com/jparklab/synology-csi/blob/09ff50643469624fd4f4eec54fd830786ef558e9/pkg/driver/nodeserver.go#L283) via #19. 
Can you try with the latest docker image(jparklab/synology-csi:latest)? You need to change the image field of the daemonset in node.yml file

**Comment by brianbuquoi** [comment] 2020-02-02 00:03
I know you didn't ask me, but I'm trying to figure out the same issue... Changed image to latest tag in node.yml and now receive the following error on **all nodes**, whereas before I had one functional.

Describe shows the following:
```
Warning  FailedMount             1s (x7 over 18s)   kubelet, starbuck        MountVolume.SetUp failed for volume "pvc-593c1a81-95a0-416e-a342-b70229a8bd38" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Failed to run ISCSI discovery: Error running iscsiadm discovery: sh: iscsiadm: not found
```

csi-plugin log shows as follows:
```
I0202 00:00:03.791492       1 iscsi.go:72] [EXECUTING] iscsiadm --mode discovery --type sendtargets --portal 10.0.1.31 --discover
I0202 00:00:03.793108       1 iscsi.go:85] Error running iscsiadm discovery: sh: iscsiadm: not found
(exit status 127)
I0202 00:00:03.793145       1 nodeserver.go:117] Failed to run ISCSI discovery: Error running iscsiadm discovery: sh: iscsiadm: not found
(exit status 127)
E0202 00:00:03.793160       1 utils.go:100] GRPC error: rpc error: code = Internal desc = Failed to run ISCSI discovery: Error running iscsiadm discovery: sh: iscsiadm: not found
(exit status 127)
```

**Comment by jparklab** [comment] 2020-02-02 00:21
@brianbuquoi it could be because of this change https://github.com/jparklab/synology-csi/commit/a1e759da2e51288f4f141c7df15bd2cec7d0ec34#diff-f951046efcea3c0431fa42139dc6a2a1. It worked when I tested in my environment. Let me change it to call /sbin/iscsiadm instead.

**Comment by brianbuquoi** [comment] 2020-02-02 00:31
I went and replaced everything with the 1.17 images and was getting a different error initially - 

` MountVolume.SetUp failed for volume "pvc-593c1a81-95a0-416e-a342-b70229a8bd38" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Failed to run ISCSI login: exit status 19 `

However, after letting it sit for a little bit it started working on both nodes.

**Comment by jparklab** [comment] 2020-02-02 01:38
The issue with the latest image seems to be caused by changing the base image to Alpine instead of CentOS. There were other people experienced the same issue: https://github.com/github/hub/issues/1818
```
/host/sbin # ls -l iscsiadm
-rwxr-xr-x    1 root     root        754952 Dec 11  2018 iscsiadm
/host/sbin # ./iscsiadm
sh: ./iscsiadm: not found
```

**Comment by jparklab** [comment] 2020-02-02 01:56
@brianbuquoi I had no luck to find a way to make it work with alpine image. I reverted the image to use CentOS as base image(which is larger than alpine, but it's better to be slower than fail..)
Can you retry with the 'jparklab/synology-csi:latest' image?

**Comment by jparklab** [comment] 2020-02-02 01:58
I can't find much information with the login failure(exit status 19). It could be due to some transient issues, and is really hard to find out why unless I can reproduce it..

**Comment by bokysan** [comment] 2020-02-02 10:53
> sh: ./iscsiadm: not found
@jparklab I did change this here: https://github.com/jparklab/synology-csi/commit/a1e759da2e51288f4f141c7df15bd2cec7d0ec34#diff-b3300941a9fb462897e9ffcd01ad1ab7R53

I did not change anything in the old configmaps (for v1.15 and v1.16) though. But with new version this configmap needs to be updated.

**Comment by jparklab** [comment] 2020-02-02 14:24
@bokysan It was not because of your change. As I mentioned above(https://github.com/jparklab/synology-csi/issues/18#issuecomment-581087855), it was because of the base image change from CentOS to alpine. `iscsiadm` fails to start due to missing libraries. (which is a bit unexpected because entire directory of the host is mounted for chroot..)

I reverted the base image as a quick remediation until I can figure out what's missing in alpine.

**Comment by bokysan** [comment] 2020-02-02 16:23
Understood, however "it works on my PC" (TM) :-)

Joke aside, my base image is [armbian](https://www.armbian.com/) and `iscsiadm` works without any issues with Alpine image. 

Do we have any further feedback on the issue?

Specifically, `ldd` output would help a lot and how `iscsiadm` is ran.

**Comment by jparklab** [comment] 2020-02-02 17:46
@bokysan I made a mistake when I was checking iscsiadm inside the image created with Alpine. I thought iscsiadm was missing libraries, but it seems like I didn't chroot into /host directory(I thought I did..)
The failure was because /sbin/iscsiadm script created from configmap starts with `#!/bin/bash` and bash is not in Alpine image.
I updated the configmap, and reverted(again!) to use Alpine image.
@brianbuquoi Please update configmap `synology-csi-iscsiadm` to use `/bin/sh' instead of `/bin/bash` 
(e.g. https://github.com/jparklab/synology-csi/commit/37ac5f47fbdb1446db3fedf7d801008a109662bc#diff-966f25ff5d3fbe1c256d4d503ee758adL53)

**Comment by brianbuquoi** [comment] 2020-02-03 16:19
I'm a little confused on what you want me to be testing with here. Should I be deploying from 1.16 or 1.17 directory? If 1.16, you want me to change every instance of `jparklab/synology-csi:v1.0.0-kubernetes-1.14.1` to `jparklab/synology-csi:latest` or just in node.yml?

I've had very little success with the 1.16 directory while running on 1.17, however I can get it **partially** working with the 1.17 directory using the boky images, however run into the following when rolling out multiple StatefulSets while deploying using a helm chart. The initial StatefulSet will create and start running successfully (on apollo [node 1]), then the subsequent ones will fail as follows (on starbuck [node 2]):

```
Warning  FailedAttachVolume  26s                attachdetach-controller  Multi-Attach error for volume "pvc-e4056d51-0609-4140-8f87-ceb4c660895e" Volume is already exclusively attached to one node and can't be attached to another
```

and if I cordon the node and put them on the same node I get the following:

```
Warning  FailedMount  1s (x5 over 9s)  kubelet, apollo    MountVolume.WaitForAttach failed for volume "pvc-e4056d51-0609-4140-8f87-ceb4c660895e" : volume attachment is being deleted
```

If I scale the StatefulSet to 0 and delete the PVC and then rescale to 1 and let it recreate the PVC and deploy to the same as the original node (apollo) I get the following:

```
Warning  FailedMount       19s                    kubelet, apollo    Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config default-token-ws2vb]: timed out waiting for the condition
```

**Comment by jparklab** [comment] 2020-02-04 16:31
@brianbuquoi If you're already using yml file in 1.17 directory, you already have the correct configmap, and therefore, there's nothing you need to change. 
I also occasionally encounter the issue with StatefulSet you mentioned. Do you mind opening another issue with the description you just added? It'd be good to have a separate thread to track the issue.

**Comment by jparklab** [comment] 2020-02-05 00:33
Closing this issue as this has been resolved by @bokysan 's updates.

**Closed as completed by jparklab** 2020-02-05 00:33 UTC
